Add missing makefile, support gmake

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -87,5 +87,19 @@ do
   fi
 done
 
+printf "checking for a usable make command... "
+make --version >/dev/null 2>&1
+if [ $? -eq 0 ] ; then make="make"
+else
+    gmake --version >/dev/null 2>&1
+    if [ $? -eq 0 ] ; then make="gmake"; fi
+fi
+if [ -n "$make" ] ; then
+    echo "yes"
+else
+    echo "not found"
+    err "Please install GNU Make and add it to your PATH as either make or gmake"
+fi
+
 rm -f config.h
-make config.h
+$make config.h
